### ISSUE TITLE
OUI needs a rule to translate it from hex to string

### ISSUE THREAD

**Issue by niloda** [openBackhaul/equipment#1]
The manufacturerIdentifier attribute is defined as string in the CoreModel, but the OUI in the SFP EEPROM (or in PHY registers) is defined as an hexadecimal value of 3 bytes. So, we have to define a rule to translate the OUI in a string. For example, the hex value  01-23-45 can be translate in "012345" or in "01-02-45".

**Comment by demx8as6** [comment]
**Proposal to the 5G-xhaul call on 01st of February 2023:**

IEEE uses "-" as separator - so we go with the proposal: "AC-DE-48".

This rule will be documented in TransmitterEquipment document.

The following sentence should be added to the "To be filled with the following data ..." for the manufactureIdentifier in table of §31, 

The 3 bytes expressed in hex should be separated by hyphen. 
The most-significant-byte and most-significant-bit comes first:

Example:
```
 |        OUI              |   
 |  AC   |   DE   |   48   | hex
 10101100 11011110 01001000  bits
 |  |             
 |  most-significant-byte  
 most-significant-bit   
```

**Comment by openBackhaul** [comment]
Starting from TransmitterEquipment_i.j.k-tsp.231213.1100+spec.1 changed as decided.

**Comment by openBackhaul** [comment]
Has been updated and published in TransmitterEquipment_1.0.0-tsp.200715.1225+spec.1.doc
