### ISSUE TITLE
Expansion towards a general Equipment specification 

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/equipment#11]
It is proposed to cover the chassis and the boards, too.

**Comment by demx8as6** [comment]
**Proposal to the 5G-xhaul call on 19th of October 2022**:

Info: the "Board" is already covered by the EQUIPMENT_CATEGORY_BACKPLAIN.

Change on EquipmentAugment Model:
A new Enumeration value at the EQUIPMENT_CATEGORIES should be added:
EQUIPMENT_CATEGORY_CHASSIS

As for the other added EQUIPMENT_CATEGORIES by the EquipmentAugment model there should be not description for the new value.

**Comment by michbin** [comment]
What is the difference between the proposed `EQUIPMENT_CATEGORY_CHASSIS` and the existing `EQUIPMENT_CATEGORY_SUBRACK`?

**Comment by demx8as6** [comment]
After  discussion the differences between SUBRACK, CHASIS ODU are not clear - description should be added to the Enumeration values 

BACKPLANE
POWER_UNIT
BATTERY
FAN
CENTRAL_PROCESSING_UNIT
STORAGE_DRIVE
SENSOR
MODEM
PORT_EXPANSION_BOARD
OUTDOOR_UNIT
NOT_YET_DEFINED

**Comment by openBackhaul** [comment]
Has been updated and published in EquipmentAugment_1.0.0-tsi.240104.1330+yang.1
