### ISSUE TITLE
Name of the Vendor

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/equipment#12]
If decided to expand the TransmitterEquipment specification to cover also the chassis, it would be proposed to fill the attributes of the actualEquipment of the chassis alike the ones at the ODU (see second table in §31 ActualEquipment in the current TransmitterEquipment specification).

**Comment by demx8as6** [comment]
Additional: The vendor should be identified by its IANA Private Enterprise Number: https://www.iana.org/assignments/enterprise-numbers/enterprise-numbers
Reason: there is a working registration available and the number are maintained. It avoids for machines the impelementation for abstracting (for example) "highstreet", "highstreet technologies", "highstreet technologies GmbH".

**Comment by michbin** [comment]
Unfortunately, there are different definitions of vendor numbers or vendor organizationally unique identifiers (OUI). E.g. SFPs use the IEEE Company Identifier. 
Furthermore, the IDs are often not unique. That is, some companies have more than 1 identifier.

**Comment by demx8as6** [comment]
The uniqueness is the beauty of IANA PEN. There is a registration and maintenance process involved that' why I bring IANA PEN into the game.

**Comment by demx8as6** [comment]
**Proposal to the 5G-xhaul call on 12th of October 2022:**

Change on TransmitterEquipment in the section ActualEquipment of chapter 9 Information

from
   For ODUs, this shall include at least the following information
to
   For ODUs **and Chassis**, this shall include at least the following information

**Comment by openBackhaul** [comment]
Starting from TransmitterEquipment_i.j.k-tsp.231213.1100+spec.1 changed as decided.

**Comment by openBackhaul** [comment]
Has been updated and published in TransmitterEquipment_1.0.0-tsp.200715.1225+spec.1.doc
