### ISSUE TITLE
control-construct::equipment::actual-equipment::is-hot-swappable parameter to be defined in detail

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/equipment#14]
The conditions and constraints for calling a equipment to be hot-swappable are to be defined in more detail.

**Comment by dperezclv** [comment]
Starting point of the definition to discuss proposal "hot swappable devices are capable of being inserted or removed from a system that is running, without causing damage or affecting performance to other elements"

**Comment by openBackhaul** [comment]
**Vendors to please double check until Tuesday 29th of June, whether their equipment and mediators would support the following formulation to be added to the next release of the Equipment specification:**
"The control-construct::equipment::actual-equipment::is-hot-swappable attribute shall be set on true, if the described equipment could be inserted or removed from the running system, without causing damage, interruption or any effects on the performance of other components of the system. This characteristic shall be independent from specific administrative configuration or operational state."

**Comment by openBackhaul** [comment]
**Proposal to the 5G-xhaul call on 13th of July 2021:**
"The control-construct::equipment::actual-equipment::is-hot-swappable attribute shall be set on true, if the described equipment could be inserted or removed from the running system, without causing damage, interruption or any effects on the performance of **other** components of the system. The aforementioned characteristic shall not require any manual change on other components of the system."

**Comment by openBackhaul** [comment]
**Individual proposal after the modeling call on 6th of July:**
The following formulation shall be added to the next release of the Equipment specification:
The control-construct::equipment::actual-equipment::is-hot-swappable attribute shall be set on true, if the described equipment could be inserted or removed from the running system, without causing damage or any effects on the performance of other components of the system. The aforementioned characteristic shall not require any manual change on other components of the system. Potential traffic interruption on the interfaces supported by the component, which is being replaced, shall not matter to the value of the is-hot-swappable attribute."

**Comment by demx8as6** [comment]
**Decision on 5G-xhaul call on 21st of July:**
“The control-construct::equipment::actual-equipment::is-hot-swappable attribute shall be set on true, if the described equipment could be inserted or removed from the running system:

without the need of powering the system down or restarting it
without being damaged or causing damage to any other element in the system where the equipment is inserted/removed
without causing traffic interruption or an alteration on the performance of other components or parts of the system not directly supported by this equipment.
The aforementioned characteristic shall not require any manual change on other components of the system. Potential traffic interruption on the interfaces supported by the component, which is being replaced, shall not matter to the value of the is-hot-swappable attribute."

**Comment by demx8as6** [comment]
@openBackhaul : we did not modify the "label" as the TransmitterEquipment_1.0.0 doc needs to be change - next question: shall we contribute the text to ONF:CoreModel.

**Comment by openBackhaul** [comment]
Instead of adding aforementioned text (Decision on 5G-xhaul call on 21st of July) to some Equipment specification, an augmentation is proposed in the EquipmentAugment modeling.

**Comment by openBackhaul** [comment]
**Proposal to the 5G-xhaul call on 29th of June 2022:**  

Instead of adding aforementioned text (Decision on 5G-xhaul call on 21st of July) to the Equipment specification, it shall be added as a comment to the existing Swappability :: isHotSwappable : Boolean attribute of the Core IM.

Adding the comment shall be done by pruning and refactoring the currently used Core IM.

A new revision statement shall be added while adding the comment.

Updating the Core IM shall be coordinated with the changed required in regards with the Synchronization modelling.

**Comment by openBackhaul** [comment]
Changing the Core IM will be tracked by a corresponding [Issue in the Core IM repository](https://github.com/openBackhaul/core/issues/25).
