### ISSUE TITLE
Identifier at the original management interface to be mapped

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/equipment#16]
The name attribute at the LTP class shall also contain an instance documenting the identifier as it is used on the vendors own management interface for identifying the same logical interface. The field shall always be filled.

logical-termination-point :: name :: value-name: "ltpName"
logical-termination-point :: name :: value: ""  (empty String as a default)

Example:
            {
                "uuid": "ETH-765.2.5",
                "name": [
                    {
                        "value-name": "ltpName",
                        "value": "WAN:2/5"
                    },
                    {
                        "value-name": "externalLabel",
                        "value": "LAN5"
                    }
                ]
            },

**Comment by demx8as6** [comment]
Please see similar information for "externalLabel":

[TransmitterEquipment_1.0.0-tsp.200715.1225+spec.1.pdf](https://github.com/openBackhaul/equipment/blob/tsp/TransmitterEquipment_1.0.0-tsp.200715.1225+spec.1.pdf)

see chapter 9

**9 Information** ControlConstruct and LogicalTerminationPoint

(27) While creating an instance of ControlConstruct or LogicalTerminationPoint, an instance of the
NameAndValue datatype at the name attribute, which is inherited from the GlobalClass, shall be automatically
created and filled with valueName:“externalLabel” and value: “”(empty String).

(28) After rebooting, the interface (e.g. mediator) the last configured value shall be represented again.

**Comment by demx8as6** [comment]
**Proposal made for the 5G-xhaul call on Wednesday 26th of January 2022**

The following new sentence should be added to chapter 9 of TransmitterEquipment document at the position of sentance (28). The exsinting (28) becomes (29) and so on.

_(28) In addition a second name with the value name “ltpName” shall be instantiated and automatically filled with a string, that contains the logical- or physical interface name that is used in the vendors own management interface e.g. ltpName = “LAN 1/2/1”._

**Comment by openBackhaul** [comment]
Please find the [LtpAugment Issue#5](https://github.com/openBackhaul/ltpAugment/issues/5) proposing a more explicit and cleaner modelling.

**Comment by openBackhaul** [comment]
This issue got obsolete due to later decision in [ltpAugment issue#5](https://github.com/openBackhaul/ltpAugment/issues/5).
It has been closed without any action.
