### ISSUE TITLE
sequence-id : Uniform way of addressing equipment

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/equipment#17]
This is for linking planning data and system settings.

**Proposal to the 5G-xhaul call on 9th of February:**
Creating a new instance of name[*] attribute at the Holder, Equipment and Connector class for adding a sequence number of the respective resource according to the [linked document](https://wiki.opennetworking.org/download/attachments/265093121/proposal-sequence-id.0.2.docx?api=v2).

**Comment by demx8as6** [comment]
Note: "Examples" will be added based on Issue #18 but examples are not in scope of this issue:

**Comment by demx8as6** [comment]
Please see presentation with Examples:
https://wiki.opennetworking.org/download/attachments/265093121/portToLTP_sdn_process_20220204_SeqNr-Concept.pdf?api=v2

**Comment by openBackhaul** [comment]
**Proposal to the 5G-xhaul call on 22nd of June 2022:**
In contrary to former considerations, there shall be no additional instance in the Holder::name and Connector::name list-attributes, but explicit sequenceId attributes.

The following changes shall be made to the EquipmentAugment modelling:
- A read-only Holder_Pac :: sequenceId[1] : Integer = -1 attribute with comment "All instances of Holder in the Equipment::containedHolder attribute shall be identifiable by a locally unique sequence ID. Gaps in the sequence would be legal. Sequence IDs at the different layers of Holders and the Connector shall compose to a unique address of the resource (for instance .2.4.1.0). The same resource shall be identifiable by the same address at all devices of the same device type." shall be added.
- A read-only Connector_Pac :: sequenceId[1] : Integer = -1 attribute with comment "All instances of Connector in the Equipment::connector attribute shall be identifiable by a locally unique sequence ID. Gaps in the sequence would be legal. Sequence IDs at the different layers of Holders and the Connector shall compose to a unique address of the resource (for instance .2.4.1.0). The same resource shall be identifiable by the same address at all devices of the same device type." shall be added.

**Comment by openBackhaul** [comment]
Comment of Connector_Pac :: sequenceId has been changed in issue #25 .

**Comment by PrathibaJee** [comment]
Comment of Connector_Pac :: sequenceId and Holder_Pac :: sequenceId has been changed in issue #25 .

**Comment by openBackhaul** [comment]
Has been updated and published in EquipmentAugment_1.0.0-tsi.240104.1330+yang.1
