### ISSUE TITLE
Sequence-id examples as annex to TransmitterEquipment document

### ISSUE THREAD

**Issue by demx8as6** [openBackhaul/equipment#18]
The examples described in ...

https://wiki.opennetworking.org/download/attachments/265093121/portToLTP_sdn_process_20220204_SeqNr-Concept.pdf?api=v2

should be added to as non-normative annex to TransmitterEquipment document.

**Comment by openBackhaul** [comment]
**Proposal to the 5G-xhaul call on 5th of October 2022:**
The examples described in ...
https://wiki.opennetworking.org/download/attachments/265093121/portToLTP_sdn_process_20220204_SeqNr-Concept.pdf?api=v2
shall be converted into as non-normative annex to TransmitterEquipment specification.

**Comment by openBackhaul** [comment]
**Decision made at the 5G-xhaul call on 5th of October 2022:**
The examples described in ...
https://wiki.opennetworking.org/download/attachments/265093121/portToLTP_sdn_process_20220204_SeqNr-Concept.pdf?api=v2
shall be _updated according to issue #17_ (UPDATA made on 5th of October 2022) and converted into as non-normative annex to TransmitterEquipment specification.

**Comment by openBackhaul** [comment]
Has been updated and published in TransmitterEquipment_1.0.0-tsp.200715.1225+spec.1.doc
