### ISSUE TITLE
Augmentation of the definition of EquipmentCategory

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/equipment#19]
**Decision made at the 5G-xhaul call on 23rd of February 2022:**

The existing EquipmentCategory enumeration of the ONF Core 1.4 shall be complemented by the following values for being able to formulate proper xPath statements in the alarm severity configuration:
* BACKPLANE
* POWER_UNIT
* BATTERY
* FAN
* CENTRAL_PROCESSING_UNIT
* STORAGE_DRIVE
* SENSOR
* MODEM
* PORT_EXPANSION_BOARD
* OUTDOOR_UNIT
* NOT_YET_DEFINED

This augmentation of the identity list shall be implemented as part of an additional EquipmentAugment YANG module.

**Comment by PrathibaJee** [comment]
In the generated YANG , all the defined EQUIPMENT_CATEGORY identities are available. But they are not inheriting in EQUIPMENT_CATEGORY in the core-model.
As per the discussion in the 5G-xhaul call on 1st of June 2022:

1. The current YANG modelling for the EQUIPMENT_CATEGORY will not work as expected (that is , it is not extending the EQUIPMENT_CATEGORY in core-model).
2. We have to modify the identity EQUIPMENT_CATEGORY in the EquipmentAugment as below , 
**From :** 
identity EQUIPMENT_CATEGORY {    
description
      "none";
  }
**To :** 
identity EQUIPMENT_CATEGORY {
    **base core-model:EQUIPMENT_CATEGORY;**
    description
      "none";
  }
3. Currently there is no guideline for the UML2YANG available for this translation.
4. So , we have to do it manually or in the post processing script.

**Comment by openBackhaul** [comment]
Has been updated and published in EquipmentAugment_1.0.0-tsi.240104.1330+yang.1
