### ISSUE TITLE
label information at ControlConstruct to be harmonized with Holder

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/equipment#20]
If it would be decided not to add an instance to the name attribute at the Holder class for documenting the external label in [Equipment Issue#15](https://github.com/openBackhaul/equipment/issues/15), it would make sense documenting the external label at the ControlConstruct and the LogicalTerminationPoint also as a separate attribute.

In this case...
- §27, §28 of the TransmitterEquipment 1.0.0-tsp.200715.1225 would have to be deleted
- ControlConstruct_Pac :: externalLabel : String [1] = "External label not yet defined." has to be added to the EquipmentAugment
- LtpAugmentConfiguration :: externalLabel : String [1] = "External label not yet defined." has to be added to the LtpAugment ([LtpAugment Issue#6](https://github.com/openBackhaul/ltpAugment/issues/6))

**Comment by openBackhaul** [comment]
**Proposal to the 5G-xhaul call on 25th of May 2022:**
In contrary to former considerations, there shall be no additional instance in the ControlConstruct::name list-attribute, but an explicit externalLabel attribute.

The following changes shall be made to the EquipmentAugment modelling:
- A ControlConstructSpec class shall be added.
- An abstraction of type Specify shall be added and connect the new ControlConstructSpec class with the existing ControlConstruct and contain the target "/CoreModel:ControlConstruct:ControlConstruct".
- A ControlConstruct_Pac class shall be added.
- A composite association [1/1] shall connect from ControlConstructSpec to ControlConstruct_Pac.
- A ControlConstruct_Pac :: externalLabel : String = "External label not yet defined." attribute with comment "The externalLabel attribute is for the operator to persistently store an identifier from his documentation inside the device." shall be added.

**Comment by demx8as6** [comment]
Decision on the 5G-xhaul call on 25th of May 2022: Approved as proposed!

**Comment by openBackhaul** [comment]
Has been updated and published in EquipmentAugment_1.0.0-tsi.240104.1330+yang.1
