### ISSUE TITLE
Wrong class diagram in TransmitterEquipment specification

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/equipment#22]
The class diagram on page 7 of the TransmitterEquipment 1.0.0-tsp.200715.1225+spec.1 is in conflict with the currently valid YANG.

ActualEquipment and ExpectedEquipment are inheriting from EquipmentDetail, but not from SuperEquipment (which does not exist at all).

The following picture should be deleted from the the TransmitterEquipment specification:
![image](https://user-images.githubusercontent.com/46722892/162945619-c8d41c3b-f6e7-44d6-84bc-418f95eb1b13.png)

**Comment by demx8as6** [comment]
potential proposal
Delete the class diagram on page 7 of the TransmitterEquipment 1.0.0-tsp.200715.1225+spec.1.

**Comment by openBackhaul** [comment]
**Proposal to the 5G-xhaul call on 5th of October 2022:**
The class diagram on page 7 of the TransmitterEquipment 1.0.0-tsp.200715.1225+spec.1 shall be deleted.

**Comment by openBackhaul** [comment]
Has been updated and published in TransmitterEquipment_1.0.0-tsp.200715.1225+spec.1.doc
