### ISSUE TITLE
Statement about Technology specific operationalState attributes to be double checked

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/equipment#24]
§40 of the TransmitterEquipment 1.0.0-tsp.200715.1225 should be double checked after making some changes on the operational state attributes and learning about potentially different semantics ("available for use").

**Comment by alexandrustancu** [comment]
The existing statement in the document:
_(40) The values of all attributes, which are describing some kind of operational status inside some technology specific augmentation of the LayerProtocol class (e.g. transceiverIsOnList, autoPmdNegotiationIsOn, performanceMonitoringIsOn …), must be disabled, if the value of the LogicalTerminationPoint::operationalState attribute is disabled._

Potential proposal:
_(40) The values of all attributes, which are describing some kind of operational status inside some technology specific augmentation of the LayerProtocol class (e.g. linkIsUp, pmdNegotiationState, performanceMonitoringIsUp …), **should be ignored**, if the value of the LogicalTerminationPoint::operationalState attribute is disabled._

Reasoning:
Both global classes and local classes from the core-model inherit from the "state-model", including the operational-state. There is no need to correlate the technology specific operational state augmentations with the LTP and LP operational-state. While the LTP and the LP operational-state is disabled, the technology specific operational state augmentations are not relevant, thus should be ignored.

**Comment by openBackhaul** [comment]
**Proposal to the 5G-xhaul call on 5th of October 2022:**
The existing statement in the TransmitterEquipment 1.0.0-tsp.200715.1225 shall be changed from:
_"(40) The values of all attributes, which are describing some kind of operational status inside some technology specific augmentation of the LayerProtocol class (e.g. transceiverIsOnList, autoPmdNegotiationIsOn, performanceMonitoringIsOn …), **must be disabled**, if the value of the LogicalTerminationPoint::operationalState attribute is disabled."_  
towards  
_"(40) The values of all attributes, which are describing some kind of operational status inside some technology specific augmentation of the LayerProtocol class (e.g. linkIsUp, pmdNegotiationState, performanceMonitoringIsUp …), **should be ignored**, if the value of the LogicalTerminationPoint::operationalState attribute is disabled."_
.

**Comment by openBackhaul** [comment]
Starting from TransmitterEquipment_i.j.k-tsp.231213.1100+spec.1 changed as decided.

**Comment by openBackhaul** [comment]
Has been updated and published in TransmitterEquipment_1.0.0-tsp.200715.1225+spec.1.doc
