### ISSUE TITLE
Reduce 'sequence-id' complexity

### ISSUE THREAD

**Issue by demx8as6** [openBackhaul/equipment#25]
This is issue is related to [Equipment #17](https://github.com/openBackhaul/equipment/issues/17).

In addition please see the following document: https://wiki.opennetworking.org/download/attachments/265093121/proposal-sequence-id.0.3.docx?api=v2

In order to reduce complexity and dependencies between between different sequence-id values related to the same Equipment object. the UML:Comment (yang:description) should be changed for _Holder_Pac::sequenceId_ and _Connector_Pac::sequenceId_.

The target is that the sequence-id values of Holders and Connectors can overlap even of the same Equipment object.

The following examples is allowed:

- Equipment::uuid = "1234"
  - Holder::sequenceId = 1
  - Holder::sequenceId = 2
  - Holder::sequenceId = 4
  - Connector::sequenceId= 0 
  - Connector::sequenceId= 1 
  - Connector::sequenceId= 2

**Comment by ThomasSeitz** [comment]
1st remark:
Maybe it make sense to add following aspect:
All devices of one device type shall be sequenced identically.

2nd remark:
There is an typo in the second sentence: The 'sequence'd'

**Comment by demx8as6** [comment]
> 1st remark: Maybe it make sense to add following aspect: All devices of one device type shall be sequenced identically.
[sko] I would like to avoid such statement, because we need to deal with the situation that the implementation based on the SoftwarePackageVersion of the device and/or of the SoftwareVersion of the Mediator.
 
> 2nd remark: There is an typo in the second sentence: The 'sequence'd'
[sko] yep - and sorry - this typo in in the comment for Connector_Pac and Holder_Pac

@openBackhaul: I'm not allwwed to edit the Proposal Text  Could you please do so - Thanks!!! :)

**Comment by demx8as6** [comment]
Proposal to the 5G-xhaul call on 27th of July 2022:

Change Holder_Pac::sequenceId comment

from

"All instances of Holder in the Equipment::containedHolder attribute shall be identifiable by a locally unique sequence ID. Gaps in the sequence would be legal. Sequence IDs at the different layers of Holders and the Connector shall compose to a unique address of the resource (for instance .2.4.1.0). The same resource shall be identifiable by the same sequence ID at all devices of the same device type."

to

"All instances of Holder in the Equipment::containedHolder attribute shall be identifiable by a unique 'sequenceId'. The 'sequenceId' should be unique for the list of Holder objects of the Equipment object. Gaps in the sequence would be legal."

Change _Connector_Pac::sequenceId comment

from

All instances of Connector in the Equipment::connector attribute shall be identifiable by a locally unique sequence ID. Gaps in the sequence would be legal. Sequence IDs at the different layers of Holders and the Connector shall compose to a unique address of the resource (for instance .2.4.1.0). The same resource shall be identifiable by the same sequence ID at all devices of the same device type."

to

All instances of Connector in the Equipment::connector attribute shall be identifiable by a locally unique 'sequenceId'. The 'sequenceId' should be unique for the list of Connector objects of the Equipment object. Gaps in the sequence would be legal."

**Comment by openBackhaul** [comment]
Has been updated and published in EquipmentAugment_1.0.0-tsi.240104.1330+yang.1.zip
