### ISSUE TITLE
IpInterface Instantiation 

### ISSUE THREAD

**Issue by demx8as6** [openBackhaul/equipment#27]
Existing definitions for Equipment and Instantiations have to be completed by definitions for the instantiation of IpInterfaces.

Potential Solution:
IpInterfaces get automatically instantiated in corresponding numbers as soon as ExpectedEquipment, which offers such interfaces, gets instantiated.

**Comment by openBackhaul** [comment]
**Proposal to the 5G-xhaul call on 10th of May 2023:**
In regards with ruling the instantiation of the LTP(IpInterface), 
- the existing formulation in paragraph _LogicalTerminationPoint and LayerProtocol_ in Chapter 6 _Instantiation_ of the Transmitter Equipment Specification  

is already covering the request for automatically creating the IpInterfaces as soon as there is an entry into the expected equipment list.

The following additional example shall be added after the already existing example 11.  
- "Example 12: One or several IpInterfaces shall be automatically created by the device for representing the OaM interface(s) towards the device."  

The following footnote shall be added to example 12:
- "The examples do not have normative character. Some implementations might provide separate connectors for management purposes, others might separate management by VLAN from other traffic on conventional payload connectors."

Rulings for instantiating an IpForwardingDomain are not required as there is no IpForwardingDomain  defined yet.

**Comment by openBackhaul** [comment]
Starting from TransmitterEquipment_i.j.k-tsp.231213.1100+spec.1 changed as decided.

**Comment by openBackhaul** [comment]
Has been updated and published in TransmitterEquipment_1.0.0-tsp.200715.1225+spec.1.doc
