### ISSUE TITLE
AirEquipment

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/equipment#3]
Existing definitions for the WireEquipment have to be complemented by definitions for the AirEquipment.

**Comment by demx8as6** [comment]
**Proposal to the 5G-xhaul call on 11th of January 2023:**

- A new example should be added to paragraph 7 for AirInterface very similar to WireInterface.
The following text should be added as Example 12 after Existing example 11:

``
Example ??: As soon as an ExpectedEquipment object representing a radio has been
instantiated, the device shall automatically instantiate a related LTP(AirInterface)[foodnote-below1].
In addition the LTP(PureEthernetStructure)[7] or the LTP(HybirdMwStructure)[foodnote-below2] shall be instantiated including the client/server relationships based on the device capabilities. 
``

- The following 2 footnotes should be added to explain the meaning of LTP(AirInterface) and LTP(HybirdMwStructure).


```
[footnote-below1]
LTP(AirInterface) = LogicalTerminationPoint and LayerProtocol object, which are augmented by technology
specific information about a AirInterface and the value of its layerProtocolName attribute =
“LAYER_PROTOCOL_NAME_TYPE_AIR_LAYER”.

[footnote-below2]
LTP(HybirdMwStructure) = LogicalTerminationPoint and LayerProtocol object, which are augmented by technology
specific information about a HybirdMwStructure and the value of its layerProtocolName attribute =
LAYER_PROTOCOL_NAME_TYPE_HYBRID_MW_STRUCTURE_LAYER”.

```

**Comment by openBackhaul** [comment]
Starting from TransmitterEquipment_i.j.k-tsp.231213.1100+spec.1 changed as decided.

**Comment by openBackhaul** [comment]
Has been updated and published in TransmitterEquipment_1.0.0-tsp.200715.1225+spec.1.doc
