### ISSUE TITLE
Equipment Reset

### ISSUE THREAD

**Issue by demx8as6** [openBackhaul/equipment#31]
**Notes from call on 2023-09-26**

- Reset on device exists - preferred also on component level
- required for "normal operation"
- warm reset
- cold reset
- check firmware update
- Equipment RPC proposal after check AI Martin ->
- Propose to do it for 2.1

**Results of checking existing Firmware RPCs**

- Firmware is currently not part of the ["Summary of Issues"](https://github.com/openBackhaul/core/wiki/Summary-of-issues) -> a new row added 
- The firmware RPC 'activate-firmware-component' describes "Operation for activating some firmware component on the device. (Attention! Invoking this operation might cause the device to reboot.)"
- Conclusion: this RPC cant be used for Equipment Reset therefor a new RPC would be needed.

**Further thoughts**
- cold vs warm start: Typically in a cold start the configuration gets lost which makes such operation very critical when evoked automatically and from remote
  - consequently a "cold start" must not be part of the model
- RPCs in the 5G-xHaul models require a parameter on which object instance in the data tree the RPC is invoked.
  - consequently the RPC must have one parameter defining the Equipment Object.
  - The next question is about the type of such Parameter to identify the equipment
     - The option 'instance-identifier' is too abstract as it would offer an RPC on all kinds of objects.
     - Typically the UUID of a the ONF:GlobalClass identifies an object instance.
        - Problem: UUIDs apply to all kind of objects, so a further constrain is needed - a when-statement that the object must be in the EquipmentList. This model should be used - the alternative to use an xPath should not be used supporting the UML2YANG process.  
- Description/Comment: As inspiration here the yang description of an RPC called "reset" from O-RAN Alliance WG4 FrontHaul:
  `"Management plane triggered restart of the radio unit. A server SHOULD send an RPC reply to the client before restarting the system."`
- As suggested the modelling and its discussion should be done in the context of version 2.1 - therefore the label is "on_hold"

**Comment by demx8as6** [comment]
Device level
Equipment level (optional, but modelled)

RPC restart ( warm vs cold, normal/force, parameter ref to an IdentityRef)

IdentityRef: ControlConstuct and Equipment

- to make more save
- the second parameter should not be optional - 
-- ref to ControlConstruct or UUID of IDU -> device level
-- ref to Equipment -> equipment level

uncommitted changes and restart
- uncommitted changes would be lost

ongoing DB operation and restart
- danger!!!! 
-- normal - nothing happens until the operation is finished
-- force - data gets lost

Schedule/delay a reset function?
-> should be more a function on application layer

EquipmentAugment should be the model

**Comment by openBackhaul** [comment]
**Proposal to the 5G-xhaul call on 10th of January 2024:**
An interface of the name EquipmentOperations to be created.  
An RPC of the name restart() to be created in EquipmentOperations.  
The restart() RPC shall have two input parameters:  
- kindOfRestart:RestartType[1] with comment "For distinguishing traffic affecting and non-traffic affecting restart."  
- affectedComponentPath:InstanceIdentifier[1] with comment "Path to the Equipment object that shall be restarted. If some top level equipment would be referenced, the entire device might be restarted."  
A RestartType enumeration shall be created and hold two values:
- COLD with comment "Service affecting restart of the device or component."
- WARM with comment "Non-service affecting restart of the device or component."

**Comment by openBackhaul** [comment]
Has been updated and published in EquipmentAugment_1.0.0-tsi.240104.1330+yang.1.zip
