### ISSUE TITLE
PureEthernetStructure

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/equipment#4]
Existing definitions for the WireEquipment respectively the instantiation of WireInterfaces have to be completed by definitions about the instantiation of PureEthernetStructures.

Potential Solution:
A PureEthernetStructure could be automatically instantiated with every WireInterface and also with every AirInterface (if the feature statements says that it is a pure Ethernet microwave).

**Comment by demx8as6** [comment]
A new paragraph or even a new section shall be created for TransmitterEquipment.

**Comment by demx8as6** [comment]
**Proposal to the 5G-xhaul call on 25th of January 2023:**

The instantiation of the PureEthernetStructure LTPs and ist server and client-LTP associations are already covered in several example of the latest version of the TransmitterEquipment document (https://github.com/openBackhaul/equipment/blob/tsp/TransmitterEquipment_1.0.0-tsp.200715.1225+spec.1.pdf).

It is proposed to close the issue without further activity.
