### ISSUE TITLE
Ethernet connection to ODU non foreseen on TransmitterEquipment specification

### ISSUE THREAD

**Issue by DanielaSpreafico** [openBackhaul/equipment#40]
On TransmitterEquipment specification it is reported the following:

1. In case of split-mount, the IF port is represented by an instance of Holder and the ODU by a subordinate instance of Equipment.

2. Example 10: As soon as an ExpectedEquipment object, which is representing an SFP, has been instantiated, the device shall automatically instantiate, LTP(WireInterface) and LTP(PureEthernetStructure).

Nothing is reported in case the connection IDU-ODU is using an Ethernet cable (both electrical or optical).
How to allow the configuration of an ODU connected to an rj45 or SFP ?

**Comment by openBackhaul** [comment]
Has been solved and decided in the following issues:
- [Connecting ODUs at Ethernet Interface (AirInterface #64)](https://github.com/openBackhaul/airInterface/issues/64)  
- [Layer 1 Aggregation (AirInterface #65)](https://github.com/openBackhaul/airInterface/issues/65)  
- [Simple Forwarding (AirInterface #66)](https://github.com/openBackhaul/airInterface/issues/66)  
- [Holder_Pac::_oduConnector [0..1] (Equipment #56)](https://github.com/openBackhaul/equipment/issues/56)  
- [Connector_Pac::_connectedOdu [0..1] (Equipment #57)](https://github.com/openBackhaul/equipment/issues/57)
