### ISSUE TITLE
EthernetContainer

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/equipment#5]
Existing definitions for the WireEquipment respectively the instantiation of WireInterfaces have to be completed by definitions about the instantiation of EthernetContainers.

Potential Solution:
An EthernetContainer could be automatically instantiated with every PureEthernet or HybridMwStructure.

**Comment by Nzein** [comment]
we understand the following steps take place in instantiating EthernetContainers.
1) Start-up equipment or Creates WireEquipment in SDN Controller
2) WireInterface or AirIterface related to 1) is instantiated.
3) PureEthernetStructure or HybridMWStructure related to 2) is instantiated.
4) EthernetContainer related to 3) is instantiated.

As such, we think there is no need to change the model for this. But we propose to add clear guidance such as the steps above to instantiate EthernetContainer in TR-532 or TR-545.
