### ISSUE TITLE
MacInterface and IpInterface Instantiation

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/equipment#6]
Existing definitions for Equipment and Instantiations have to be completed by definitions for the instantiation of MacInterfaces and IpInterfaces.

Potential Solution:
MacInterfaces and IpInterfaces get automatically instantiated in corresponding numbers as soon as ExpectedEquipment, which offers such interfaces, gets instantiated.

**Comment by demx8as6** [comment]
regarding IP - it is deferred for future use - 2.1 
- for IP a new issue should be created to be addressed in future.
- Please see https://github.com/openBackhaul/equipment/issues/27

regrading MacInterface
- please see MAC related paragraphs of [Equipment #7](https://github.com/openBackhaul/equipment/issues/7) 

The following sentence should be considered to address this issue:

"As soon as an ExpectedEquipment object, which is representing an Ethernet Switch with four internal interfaces, has been instantiated, the device shall automatically instantiate four LTP(EthernetContainer), four LTP(MacInterface) and four LTP(VlanInterface) (only in case the device supports VLAN bridging)."

**Comment by demx8as6** [comment]
**Proposal made to the 5G-xhaul call on 14th of December 2022**

The issue should be spitted into 2 parts - one for IPInterfaces and one for MacInterfaces
The IpInterface part should be covered by https://github.com/openBackhaul/equipment/issues/27

The MacInterface part was already covered by https://github.com/openBackhaul/equipment/issues/7

This issue should be closed without further activity.
