### ISSUE TITLE
VlanInterface, VlanFd and VlanFc

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/equipment#7]
Existing definitions for Equipment and Instantiations have to be completed by definitions for the instantiation of VlanInterface and Profiles.

Since they are seemingly not dependent on any ExpectedEquipment (at least in number) a different proceeding would be required.

UPDATE 2nd of November 2022: In contrary to what's stated above VlanInterface and VlanFD are dependent on the ExpectedEquipment. There shall be a VlanInterface on top of every MacInterface (if the device is supporting VLAN). There shall be one VlanFD. Starting from here VlanFc and FcPorts have to be created by calling RPCs.

**Comment by demx8as6** [comment]
Regarding Instantiation for VlanInterface.
- From CoreModel point of view the Instantiation of an VlanInterface is not (must not be) different like the instantiation for all other interfaces.
- Either they are created with the equipment which wont be the case for VlanInterfaces
- or the are created with a NETCONF <edit-config> (RESTCONF PUT) for an LTP with LP and the technology specific conditional package.
- known limitation: in Mediator implementations the external managed uuid cannot be stored on the device.

Options
- accept the limitation
- create VlanInterfaces using the local-craft-terminals
- create an RPC for LTP creation - the UUID is generated by the Mediator and based in a mappable ID within the device - this UUID is part of the repose to the create-RPC.
- others ?

Note:
- in case of RPC to create an LTP: such RPC should be model in LTP-Augment -> create a new issues there an put it on-hold for 2.1

Regrading Instantiations of Profiles.
For MW 2.0 possible profiles are created by the Device only - the operator can just select from the supported list.
In case a profile instance is created by a NETCONF Client - the device (NETCONF-Server) can consume or reject the related <edit-config>

Such behaviour should be described in a chapter in the "overarching" TR 532.
... to be discussed about the forward looking procedure(s)

**Comment by openBackhaul** [comment]
**Potential Proposal to be discussed with vendor representatives:**
The VlanInterface shall be automatically created together with the underlaying MacInterface ... WireInterface or AirInterface, but it shall activated depending either on an administrative state attribute or on being referenced in a FcPort.

**Comment by demx8as6** [comment]
Conclusions:
- VLAN Interfaces are created by the device/mediator based on the first entry in the expected equipment list.
- A 1:1 relationship between MacInterfaces and VlanInterfaces is expected.
- FD sublayers and VLAN interface sublayer attributes can be modified. No extra RPC definition required. 
- Behaviour of the object classes (e.g LTP, FD, FC, FC-PORTs)  after altering the sublayer attributes depends on the device implementation. 
- Change on the model: adding a parameter for "forwaredCVlanListByDefaultSVlanId" to the VLANInterface in case of "Provider Edge Bridge" and VLANInterface::sublayer equals to C-VLAN. This topic should be handled as issue in VLAN-Interface repo.

**Comment by openBackhaul** [comment]
**In regards with LTP:**
In principle, paragraph _LogicalTerminationPoint and LayerProtocol_ in Chapter 6 _Instantiation_ of the Transmitter Equipment Specification is so generic that it also covers the 1:1 relationship between MacInterfaces and VlanInterfaces.
Maybe (technical background has to be checked), MacInterface and VlanInterface could be additionally mentioned in Example 10.

**In regards with FD:**
An additional paragraph _ForwardingDomain and ForwardingConstruct_ should be added behind the paragraph _LogicalTerminationPoint and LayerProtocol_. It might start with:
_"(8) As soon as an ExpectedEquipment object has been instantiated, the device shall automatically instantiate all ForwardingDomain objects (including technology specific augments), which are unquestionable related with this hardware._
_(9) Already existing configurations of forwarding shall automatically be expressed by instances of ForwardingConstructs and FcPorts, which are referencing the connected LogicalTerminationPoints."_

**Comment by openBackhaul** [comment]
**Potential Proposal:**
In regards with LTP, 
- the existing formulation in paragraph _LogicalTerminationPoint and LayerProtocol_ in Chapter 6 _Instantiation_ of the Transmitter Equipment Specification is already covering the request for automatically creating the VlanInterfaces as soon as there is an entry into the expected equipment list. So, no change required.

... to be continued ...

**Comment by openBackhaul** [comment]
Starting from TransmitterEquipment_i.j.k-tsp.231213.1100+spec.1 changed as decided.

**Comment by openBackhaul** [comment]
Has been updated and published in TransmitterEquipment_1.0.0-tsp.200715.1225+spec.1.doc
