### ISSUE TITLE
Root instantiation

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/equipment#8]
Existing definitions for Equipment and Instantiations have to be completed by definitions about the logical objects that have to exist even at a "new born" or hard-reseted Devices.

Potential Solution:
Apart from the ControlConstruct, all the Equipment, which is already present as ActualEquipment, must be instantiated plus the associated interfaces (see lower number issues).

**Comment by alexandrustancu** [comment]
In the _TransmitterEquipment_1.0.0-tsp.200715.1225+spec.1.pdf_ document, the described problem is already covered by points (3), (5), (7), (8), (9), (10), (11), i.e. it is specified that ActualEquipment instances need to be instantiated when hardware is present in the device, along with all the associated interfaces, with the remark that doing the same upon reboot is not explicitly mentioned.

Potential proposal:

Adding a point explicitly mentioning that the ControlConstruct and all the ActualEquipment instances need to be present upon boot: "(0) _ControlConstruct as well as ActualEquipment associated with hardware already present in the device shall be instantiated as the device is booting up._"

**Comment by openBackhaul** [comment]
**Proposal to the 5G-xhaul call on 19th of October 2022:**
Adding a point explicitly mentioning that the ControlConstruct and all the ActualEquipment instances need to be present upon boot: _"(0) ControlConstruct as well as ActualEquipment associated with hardware already present in the device shall be instantiated as the device is booting up."_

(Numbering of the paragraphs shall be updated after all changes have been incorporated.)

**Comment by openBackhaul** [comment]
Starting from TransmitterEquipment_i.j.k-tsp.231213.1100+spec.1 changed as decided.

**Comment by openBackhaul** [comment]
Has been updated and published in TransmitterEquipment_1.0.0-tsp.200715.1225+spec.1.doc
